### ISSUE TITLE
Releases for 3.11 and 3.12 ?

### ISSUE THREAD

**Issue by stuaxo** [marazmiki/s3-parse-url#3]
Hi,
  Any chance of a new release to cover 3.11 and 3.12 ?

Cheers
Stuart

**Comment by marazmiki** [comment]
Actually, I'm pretty sure it would work perfectly both on 3.11 and 3.12

But yes, it makes sense to make a special release to embrace it. Will do it ASAP

**Comment by marazmiki** [comment]
Oh, forgot to say. It has been released
